openapi: 3.2.0
info:
  title: Customer Health API
  description: '# Introduction

    API for Echo Customers.'
  version: v2.1.3-main
  contact:
    name: Echo Global Logistics
    url: https://www.echo.com
    email: info@echo.com
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/echogl/Customer_API_OAuth_Public/v2.1.3-main
- url: https://customerapi.echo.com
  description: Production server
tags:
- name: Health
paths:
  /v2/__health:
    get:
      operationId: Health.show
      description: Used for checking healthy/unhealthy endpoints.
      summary: Used for checking healthy/unhealthy endpoints
      tags:
      - Health
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                description: A health response
                type: object
                properties:
                  healthChecks:
                    type: object
                    properties:
                      parentService:
                        type: object
                        properties:
                          healthy:
                            type: array
                            description: healthy services
                            items:
                              type: string
                          unhealthy:
                            type: array
                            description: unhealthy services
                            items:
                              type: string
                          description:
                            type: string
                            description: summary of healthy/unhealthy services
                example:
                  health_checks:
                    CustomerAPI:
                      healthy:
                      - get_quote
                      - generate_quote
                      unhealthy: []
                      description: CustomerAPI is healthy
components:
  securitySchemes:
    customer_api_authorizer_post:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: custom
    customer_api_authorizer_get:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: custom
x-tagGroups:
- name: Core APIs
  tags:
  - quotes
  - health
- name: CORS Support
  tags:
  - CORS
