openapi: 3.2.0
info:
  title: Customer Quotes API
  description: '# Introduction

    API for Echo Customers.'
  version: v2.1.3-main
  contact:
    name: Echo Global Logistics
    url: https://www.echo.com
    email: info@echo.com
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/echogl/Customer_API_OAuth_Public/v2.1.3-main
- url: https://customerapi.echo.com
  description: Production server
tags:
- name: Quotes
  description: Used for creating and retrieving quotes.
paths:
  /v2/quotes/{id}:
    get:
      operationId: Quote_v2.show
      description: Used for retrieving quotes.
      summary: Used for retrieving quotes
      tags:
      - Quotes
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: A quote response
                type: object
                required:
                - quote
                properties:
                  quote:
                    type: object
                    allOf:
                    - required:
                      - status
                      - quoteNumber
                      - quoteKey
                      - quoteId
                      - createdDate
                      - expirationDate
                      - stops
                      - serviceOptions
                      type: object
                      properties:
                        status:
                          type: string
                          description: The status of the quote.
                          enum:
                          - pending
                          - open
                        quoteId:
                          type: string
                          description: Human-readable quote number.
                          example: AB35C7CX98
                        quoteKey:
                          type: string
                          description: The unique key of the quote
                          example: 42a815ef1b444504b422b0dc24e44f8a
                        quoteNumber:
                          type: string
                          description: Human-readable quote number.
                          example: AB35C7CX98
                        createdDate:
                          type: string
                          format: date-time
                          description: The creation date of the quote. (RFC 3339)
                        expirationDate:
                          type: string
                          description: The expiration date of the quote. (RFC 3339)
                          format: date-time
                          example: '2019-05-09T18:43:21.226-06:00'
                        stops:
                          type: array
                          minItems: 2
                          items:
                            type: object
                            properties:
                              stopNumber:
                                type: integer
                                minimum: 1
                                example: 1
                              stopType:
                                type: string
                                enum:
                                - pick
                                - drop
                              postalCode:
                                type: string
                                minLength: 5
                              country:
                                type: string
                                enum:
                                - us
                              serviceWindow:
                                type: object
                                properties:
                                  startDate:
                                    type: string
                                    format: date
                        serviceOptions:
                          type: array
                          items:
                            type: object
                            properties:
                              serviceOptionId:
                                type: integer
                                example: 1
                              currencyType:
                                type: string
                                enum:
                                - usd
                              transitTimeInDays:
                                type: integer
                                example: 3
                              totalMileage:
                                type: number
                                example: 2075
                              pickupDate:
                                type: string
                                format: date
                              mode:
                                type: string
                                enum:
                                - tl
                              totalCost:
                                type: number
                              equipment:
                                type: string
                                enum:
                                - van_dry_53
                                - reefer_53
                                - flatbed_48
                              isHazmat:
                                type: boolean
                                default: false
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden Invalid Token or API Key
        '404':
          description: Not found
        '500':
          description: Server not found
        '503':
          description: Service unavailable
      security:
      - customer_api_authorizer_get: []
  /v2/quotes:
    post:
      operationId: Quote_v2.create
      description: Used for creating quotes.
      summary: Used for creating quotes
      tags:
      - Quotes
      parameters:
      - in: header
        name: X-Echo-Channel-Id
        schema:
          type: string
        required: false
      - in: header
        name: X-Echo-System-Id
        schema:
          type: string
        required: false
      requestBody:
        content:
          application/json:
            schema:
              description: A quote request
              type: object
              required:
              - modes
              - stops
              properties:
                modes:
                  type: array
                  items:
                    type: string
                    enum:
                    - tl
                stops:
                  type: array
                  minItems: 2
                  items:
                    type: object
                    properties:
                      stopNumber:
                        type: integer
                        minimum: 1
                      stopType:
                        type: string
                        enum:
                        - pick
                        - drop
                      postalCode:
                        type: string
                        minLength: 5
                      country:
                        type: string
                        enum:
                        - us
                      serviceWindow:
                        type: object
                        properties:
                          startDate:
                            type: string
                            format: date
                equipment:
                  type: string
                  enum:
                  - van_dry_53
                  - reefer_53
                  - flatbed_48
                isHazmat:
                  type: boolean
                  default: false
        required: true
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Invalid token or API key
        '404':
          description: Not found
        '422':
          description: Service options not found
        '500':
          description: Server not found
        '502':
          description: Bad gateway
        '503':
          description: Service unavailable
      security:
      - customer_api_authorizer_post: []
components:
  securitySchemes:
    customer_api_authorizer_post:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: custom
    customer_api_authorizer_get:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: custom
x-tagGroups:
- name: Core APIs
  tags:
  - quotes
  - health
- name: CORS Support
  tags:
  - CORS
