openapi: 3.0.0
info:
  contact:
    name: Echo Global Logistics
    url: https://www.echo.com
    email: info@echo.com
  version: 1.0.0
  title: Echo Authorizer documents health API
  description: 'All API operations require an access token to be passed in the Authorization Header for each request. The token type is an OAuth 2.0 Bearer token. To get the token you have to call the /token operation of this API and provide **client_id** and **client_secret**.


    **`Access Token Lifecycle:`** When you recieve an Access Token, it is valid for defined amount of time. The expiration time for the token is returned in the response along with the bearer token.  Developers should implement the client application in a way that  token will be requested again only after it expires. During this time you don''t have to request new token per each request, but you can simply reuse the same token to access API resources, until the token expires. The invalid token or token expiration will be indicated by HTTP Status Code 401 Unauthorized, then your application has to request new Access token.


    **`Access Token Request Rate Limiting:`** The Access Token should be used for the lifetime of the token until it has expired. Partners requesting new tokens multiple times in an hour may be subject to rate limiting.


    **`API Request Rate Limiting:`** Please do not exceed more than 3 requests per second. Partners who exceed this limit may be subject to rate limiting.'
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/echogl/Echo_Authorizer_Public/1.0.0
- description: Production environment.
  url: https://auth.echo.com
tags:
- name: health
paths:
  /v2/__health:
    get:
      operationId: Health.show
      description: Used for checking healthy/unhealthy endpoints.
      summary: Used for checking healthy/unhealthy endpoints.
      tags:
      - health
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                description: A health response
                type: object
                properties:
                  healthChecks:
                    type: object
                    properties:
                      parentService:
                        type: object
                        properties:
                          healthy:
                            type: array
                            description: healthy services
                            items:
                              type: string
                          unhealthy:
                            type: array
                            description: unhealthy services
                            items:
                              type: string
                          description:
                            type: string
                            description: summary of healthy/unhealthy services
                example:
                  health_checks:
                    CustomerAPI:
                      healthy:
                      - get_quote
                      - generate_quote
                      unhealthy: []
                      description: CustomerAPI is healthy
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    apiKey:
      type: apiKey
      name: x-api-key
      in: header
